import os
from pathlib import Path
from typing import Any

from sqlalchemy import create_engine, text


SQLITE_PATH = Path(__file__).resolve().parent.parent / "opspilot.db"

database_url = os.getenv("DATABASE_URL")

if database_url:
    if database_url.startswith("postgresql://"):
        database_url = database_url.replace(
            "postgresql://",
            "postgresql+psycopg://",
            1,
        )

    DATABASE_URL = database_url
else:
    DATABASE_URL = f"sqlite:///{SQLITE_PATH.as_posix()}"


engine = create_engine(
    DATABASE_URL,
    pool_pre_ping=True,
)


def initialize_database() -> None:
    with engine.begin() as connection:
        connection.execute(
            text(
                """
                CREATE TABLE IF NOT EXISTS invoices (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    vendor TEXT NOT NULL,
                    department TEXT NOT NULL,
                    amount DOUBLE PRECISION NOT NULL,
                    status TEXT NOT NULL,
                    risk TEXT NOT NULL
                )
                """
            )
            if DATABASE_URL.startswith("postgresql")
            else text(
                """
                CREATE TABLE IF NOT EXISTS invoices (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    vendor TEXT NOT NULL,
                    department TEXT NOT NULL,
                    amount REAL NOT NULL,
                    status TEXT NOT NULL,
                    risk TEXT NOT NULL
                )
                """
            )
        )

        count = connection.execute(
            text(
                """
                SELECT COUNT(*) AS count
                FROM invoices
                """
            )
        ).scalar_one()

        if count == 0:
            seed_invoices = [
                {
                    "vendor": "Northstar Systems",
                    "department": "Technology",
                    "amount": 14850,
                    "status": "Pending",
                    "risk": "High",
                },
                {
                    "vendor": "BrightPath Consulting",
                    "department": "Operations",
                    "amount": 8200,
                    "status": "Review",
                    "risk": "Medium",
                },
                {
                    "vendor": "Capital Office Supply",
                    "department": "Finance",
                    "amount": 3940,
                    "status": "Approved",
                    "risk": "Low",
                },
                {
                    "vendor": "Summit Data Group",
                    "department": "Technology",
                    "amount": 11400,
                    "status": "Pending",
                    "risk": "Medium",
                },
                {
                    "vendor": "Vertex Security",
                    "department": "Technology",
                    "amount": 6750,
                    "status": "Pending",
                    "risk": "High",
                },
                {
                    "vendor": "Blue Ridge Logistics",
                    "department": "Operations",
                    "amount": 4200,
                    "status": "Pending",
                    "risk": "Low",
                },
                {
                    "vendor": "Pioneer Analytics",
                    "department": "Finance",
                    "amount": 9800,
                    "status": "Pending",
                    "risk": "Medium",
                },
                {
                    "vendor": "Metro Facilities",
                    "department": "Facilities",
                    "amount": 12500,
                    "status": "Approved",
                    "risk": "Low",
                },
            ]

            connection.execute(
                text(
                    """
                    INSERT INTO invoices (
                        vendor,
                        department,
                        amount,
                        status,
                        risk
                    )
                    VALUES (
                        :vendor,
                        :department,
                        :amount,
                        :status,
                        :risk
                    )
                    """
                ),
                seed_invoices,
            )


def replace_invoices(
    invoices: list[dict[str, Any]],
) -> int:
    with engine.begin() as connection:
        connection.execute(
            text("DELETE FROM invoices")
        )

        connection.execute(
            text(
                """
                INSERT INTO invoices (
                    vendor,
                    department,
                    amount,
                    status,
                    risk
                )
                VALUES (
                    :vendor,
                    :department,
                    :amount,
                    :status,
                    :risk
                )
                """
            ),
            invoices,
        )

    return len(invoices)


def get_all_invoices() -> list[dict[str, Any]]:
    with engine.connect() as connection:
        rows = connection.execute(
            text(
                """
                SELECT
                    id,
                    vendor,
                    department,
                    amount,
                    status,
                    risk
                FROM invoices
                ORDER BY amount DESC
                """
            )
        ).mappings().all()

    return [
        dict(row)
        for row in rows
    ]


def get_recent_invoices(
    limit: int = 8,
) -> list[dict[str, Any]]:
    records = get_all_invoices()

    records.sort(
        key=lambda record: record["id"],
        reverse=True,
    )

    return records[:limit]


def get_dashboard_summary() -> dict[str, Any]:
    records = get_all_invoices()

    return {
        "total_invoices": len(records),
        "pending_invoices": sum(
            1
            for record in records
            if record["status"].lower() == "pending"
        ),
        "high_risk_invoices": sum(
            1
            for record in records
            if record["risk"].lower() == "high"
        ),
        "total_spend": round(
            sum(
                float(record["amount"])
                for record in records
            ),
            2,
        ),
        "department_count": len(
            {
                record["department"]
                for record in records
            }
        ),
    }


def get_risk_distribution() -> list[dict[str, Any]]:
    records = get_all_invoices()

    groups: dict[str, int] = {}

    for record in records:
        risk = record["risk"]

        groups[risk] = groups.get(risk, 0) + 1

    return sorted(
        [
            {
                "risk": risk,
                "count": count,
            }
            for risk, count in groups.items()
        ],
        key=lambda item: item["count"],
        reverse=True,
    )


def get_status_distribution() -> list[dict[str, Any]]:
    records = get_all_invoices()

    groups: dict[str, int] = {}

    for record in records:
        status = record["status"]

        groups[status] = groups.get(status, 0) + 1

    return sorted(
        [
            {
                "status": status,
                "count": count,
            }
            for status, count in groups.items()
        ],
        key=lambda item: item["count"],
        reverse=True,
    )


def get_department_spending(
    department: str | None = None,
) -> list[dict[str, Any]]:
    records = get_all_invoices()

    if department:
        records = [
            record
            for record in records
            if record["department"].lower()
            == department.lower()
        ]

    groups: dict[str, dict[str, Any]] = {}

    for record in records:
        name = record["department"]

        if name not in groups:
            groups[name] = {
                "department": name,
                "total_spending": 0.0,
                "invoice_count": 0,
            }

        groups[name]["total_spending"] += float(
            record["amount"]
        )
        groups[name]["invoice_count"] += 1

    results = list(groups.values())

    for result in results:
        result["total_spending"] = round(
            result["total_spending"],
            2,
        )

    results.sort(
        key=lambda item: item["total_spending"],
        reverse=True,
    )

    return results


def get_vendor_spending(
    vendor: str | None = None,
) -> list[dict[str, Any]]:
    records = get_all_invoices()

    if vendor:
        records = [
            record
            for record in records
            if record["vendor"].lower()
            == vendor.lower()
        ]

    groups: dict[str, dict[str, Any]] = {}

    for record in records:
        name = record["vendor"]

        if name not in groups:
            groups[name] = {
                "vendor": name,
                "total_spending": 0.0,
                "invoice_count": 0,
            }

        groups[name]["total_spending"] += float(
            record["amount"]
        )
        groups[name]["invoice_count"] += 1

    results = list(groups.values())

    for result in results:
        result["total_spending"] = round(
            result["total_spending"],
            2,
        )

    results.sort(
        key=lambda item: item["total_spending"],
        reverse=True,
    )

    return results


def get_top_vendors(
    limit: int = 10,
) -> list[dict[str, Any]]:
    return get_vendor_spending()[:limit]


def analyze_invoices(
    plan: dict[str, Any],
) -> dict[str, Any]:
    records = get_all_invoices()

    departments = plan.get("departments") or []
    vendors = plan.get("vendors") or []
    risks = plan.get("risks") or []
    statuses = plan.get("statuses") or []

    min_amount = plan.get("min_amount")
    max_amount = plan.get("max_amount")

    if departments:
        department_set = {
            value.lower()
            for value in departments
        }

        records = [
            record
            for record in records
            if record["department"].lower()
            in department_set
        ]

    if vendors:
        vendor_set = {
            value.lower()
            for value in vendors
        }

        records = [
            record
            for record in records
            if record["vendor"].lower()
            in vendor_set
        ]

    if risks:
        risk_set = {
            value.lower()
            for value in risks
        }

        records = [
            record
            for record in records
            if record["risk"].lower()
            in risk_set
        ]

    if statuses:
        status_set = {
            value.lower()
            for value in statuses
        }

        records = [
            record
            for record in records
            if record["status"].lower()
            in status_set
        ]

    if min_amount is not None:
        records = [
            record
            for record in records
            if float(record["amount"])
            >= float(min_amount)
        ]

    if max_amount is not None:
        records = [
            record
            for record in records
            if float(record["amount"])
            <= float(max_amount)
        ]

    records.sort(
        key=lambda record: float(
            record["amount"]
        ),
        reverse=True,
    )

    total_spend = round(
        sum(
            float(record["amount"])
            for record in records
        ),
        2,
    )

    average_amount = (
        round(
            total_spend / len(records),
            2,
        )
        if records
        else 0
    )

    summary = {
        "count": len(records),
        "total_spend": total_spend,
        "average_amount": average_amount,
        "pending_count": sum(
            1
            for record in records
            if record["status"].lower() == "pending"
        ),
        "approved_count": sum(
            1
            for record in records
            if record["status"].lower() == "approved"
        ),
        "review_count": sum(
            1
            for record in records
            if record["status"].lower() == "review"
        ),
        "high_risk_count": sum(
            1
            for record in records
            if record["risk"].lower() == "high"
        ),
        "medium_risk_count": sum(
            1
            for record in records
            if record["risk"].lower() == "medium"
        ),
        "low_risk_count": sum(
            1
            for record in records
            if record["risk"].lower() == "low"
        ),
    }

    department_breakdown = _build_breakdown(
        records,
        "department",
    )

    vendor_breakdown = _build_breakdown(
        records,
        "vendor",
    )

    risk_breakdown = _build_simple_breakdown(
        records,
        "risk",
    )

    status_breakdown = _build_simple_breakdown(
        records,
        "status",
    )

    largest_invoice = (
        records[0]
        if records
        else None
    )

    smallest_invoice = (
        min(
            records,
            key=lambda record: float(
                record["amount"]
            ),
        )
        if records
        else None
    )

    return {
        "filters": {
            "departments": departments,
            "vendors": vendors,
            "risks": risks,
            "statuses": statuses,
            "min_amount": min_amount,
            "max_amount": max_amount,
        },
        "summary": summary,
        "department_breakdown": department_breakdown,
        "vendor_breakdown": vendor_breakdown,
        "risk_breakdown": risk_breakdown,
        "status_breakdown": status_breakdown,
        "largest_invoice": largest_invoice,
        "smallest_invoice": smallest_invoice,
        "records": records,
    }


def _build_breakdown(
    records: list[dict[str, Any]],
    field: str,
) -> list[dict[str, Any]]:
    groups: dict[str, list[dict[str, Any]]] = {}

    for record in records:
        name = str(record[field])

        groups.setdefault(
            name,
            [],
        ).append(record)

    results = []

    for name, group in groups.items():
        total_spend = round(
            sum(
                float(record["amount"])
                for record in group
            ),
            2,
        )

        average_amount = round(
            total_spend / len(group),
            2,
        )

        result = {
            field: name,
            "count": len(group),
            "total_spend": total_spend,
            "average_amount": average_amount,
            "high_risk_count": sum(
                1
                for record in group
                if record["risk"].lower() == "high"
            ),
            "medium_risk_count": sum(
                1
                for record in group
                if record["risk"].lower() == "medium"
            ),
            "low_risk_count": sum(
                1
                for record in group
                if record["risk"].lower() == "low"
            ),
            "pending_count": sum(
                1
                for record in group
                if record["status"].lower()
                == "pending"
            ),
            "approved_count": sum(
                1
                for record in group
                if record["status"].lower()
                == "approved"
            ),
            "review_count": sum(
                1
                for record in group
                if record["status"].lower()
                == "review"
            ),
        }

        results.append(result)

    results.sort(
        key=lambda item: item["total_spend"],
        reverse=True,
    )

    return results


def _build_simple_breakdown(
    records: list[dict[str, Any]],
    field: str,
) -> list[dict[str, Any]]:
    groups: dict[str, list[dict[str, Any]]] = {}

    for record in records:
        name = str(record[field])

        groups.setdefault(
            name,
            [],
        ).append(record)

    results = []

    for name, group in groups.items():
        total_spend = round(
            sum(
                float(record["amount"])
                for record in group
            ),
            2,
        )

        results.append(
            {
                field: name,
                "count": len(group),
                "total_spend": total_spend,
                "average_amount": round(
                    total_spend / len(group),
                    2,
                ),
            }
        )

    results.sort(
        key=lambda item: item["count"],
        reverse=True,
    )

    return results